### PR TITLE
Talk function and error handling improved

### PR DESCRIPTION
**Pull request by ScrabbleScratch**
The `talk(text)` function was improved. Now it is able to reproduce the message and print it on the console, or reproduce a message and don't print it, or reproduce a message and specify what to print on the console. Now the funtion is called with `talk(text, console=True, consoleText="")`, the `console` parameter is set to **True** by default so it _will always print_ to the console _unless it's set to **False**_, and the `consoleText `will be printed _only if_ `console=**False**` and `consoleText `is _not an empty string_.
With this the print() calls were reduced within the code, so is more practical to use.

The `who is` command was rising an error that was killing the program if the wikipedia page wasn't found. Now it handles the error by _printing a message on the console_ notifying about a result not found, so the program _doesn't need to be restarted to work_.

### CODE REVIEW

**Comment by NateBrownProjectsNZ** [comment]
Would you like me to approve & merge?

**Comment by ScrabbleScratch** [comment]
No, sorry!
I haven't noticed that you have already chaged the script.
Right now I'm making the changes to be merged correctly.

**Comment by NateBrownProjectsNZ** [comment]
Awesome .hmu when your happy with it

**Comment by NateBrownProjectsNZ** [comment]
Just noticed that inthe code, 'weatherhive' is a file, but there isn't one in the pull request. would you like me to add one?

**Comment by ScrabbleScratch** [comment]
It's okay. Since we are using **pyowm** it is not needed anymore. Right now I'm fixing everything to make it work.

**Comment by NateBrownProjectsNZ** [comment]
Ok. Thanks.

**Comment by ScrabbleScratch** [comment]
Now it's ready to be reviewed and merged if it is good.

**Comment by NateBrownProjectsNZ** [comment]
TypeError: argument of type 'NoneType' is not iterable. with new code. after completing a command.

**Comment by ScrabbleScratch** [comment]
Yes.
It is raised when some commands are called, it has to be reviewed since I haven't found the reasom yet.
Sometimes it is raised when the "Enter" key is pressed while executing an instruction (when it is not required to submit a command).

**Pull request merged**
